In [3]:
import numpy as np
import numpy

"""
Rectangle class that allows for easier use/access to the four coordinates of a bounding box
"""
class rectangle:
    def __init__(self, xmin, ymin, xmax, ymax):
        self.xmin = xmin
        self.ymin = ymin
        self.xmax = xmax
        self.ymax = ymax
    
    def __repr__(self):
        return str(np.array([self.xmin, self.ymin, self.xmax, self.ymax]))
    
    
    def toArray(self):
        return np.array([self.xmin, self.ymin, self.xmax, self.ymax])


In [4]:
"""
Just testing stuff
"""
dataset = []
import xml.etree.ElementTree as ET
a = []
green = []
red = []
xmin = 0
ymin = 0
xmax = 0
ymax = 0
tree = ET.parse('images_new_resized/green_new_labels/00000007.xml')
root = tree.getroot()
for child in root:
    if child.tag == 'object' :
        for subchild in child:
            if subchild.tag == 'bndbox':
                for subsubchild in subchild:
                    if subsubchild.tag == 'xmin':
                        xmin = int(subsubchild.text)
                    elif subsubchild.tag == 'ymin':
                        ymin = int(subsubchild.text)
                    elif subsubchild.tag == 'xmax':
                        xmax = int(subsubchild.text)
                    elif subsubchild.tag == 'ymax':
                        ymax = int(subsubchild.text)
                a.append(rectangle(xmin, ymin, xmax, ymax).toArray())


                
for l in range(len(a)):
    a[l] = np.array(a[l])
print(np.array(a))

[[128  64 173 132]
 [ 10 207  53 274]
 [ 59 209  96 278]
 [103 211 134 274]
 [142 212 173 272]
 [183 210 210 276]
 [217 214 247 278]
 [254 213 287 280]]


In [5]:
green_boxes = []
labels = []
for i in range(10):
    tmp = []
    tmp_label = []
    tree = ET.parse('images_new_resized/green_new_labels/0000000'+str(i)+'.xml')
    root = tree.getroot()
    for child in root:
        if child.tag == 'object' :
            for subchild in child:
                if subchild.tag == 'name':
                    if subchild.text == 'green':
                        tmp_label.append(0)
                    elif subchild.text == 'red':
                        tmp_label.append(1)
                    else:
                        print("something is wrong with "+str(i))
            for subchild in child:
                if subchild.tag == 'bndbox':
                    for subsubchild in subchild:
                        if subsubchild.tag == 'xmin':
                            xmin = int(subsubchild.text)
                        elif subsubchild.tag == 'ymin':
                            ymin = int(subsubchild.text)
                        elif subsubchild.tag == 'xmax':
                            xmax = int(subsubchild.text)
                        elif subsubchild.tag == 'ymax':
                            ymax = int(subsubchild.text)
                    tmp.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    green_boxes.append(np.array(tmp))
    if len(green_boxes) == 0:
        print(i, "B A D")
        green_boxes.append([])
        
for i in range(10,100):
    try:
        tmp = []
        tree = ET.parse('images_new_resized/green_new_labels/000000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_label.append(0)
                        elif subchild.text == 'red':
                            tmp_label.append(1)
                        else:
                            print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp.append(rectangle(xmin, ymin, xmax, ymax).toArray())
        green_boxes.append(np.array(tmp))
        if len(green_boxes) == 0:
            print(i, "B A D")
            green_boxes.append([])
    except:
        green_boxes.append([])
        
for i in range(100,480):
    try:
        tmp = []
        tree = ET.parse('images_new_resized/green_new_labels/00000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_label.append(0)
                        elif subchild.text == 'red':
                            tmp_label.append(1)
                    else:
                        print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp.append(rectangle(xmin, ymin, xmax, ymax).toArray())
        green_boxes.append(np.array(tmp))
        if len(green_boxes) == 0:
            green_boxes.append([])
            print(i, "B A D")
    except:
        green_boxes.append([])
        


something is wrong with 100
something is wrong with 100
something is wrong with 100
something is wrong with 100
something is wrong with 102
something is wrong with 102
something is wrong with 102
something is wrong with 102
something is wrong with 103
something is wrong with 103
something is wrong with 103
something is wrong with 103
something is wrong with 104
something is wrong with 104
something is wrong with 104
something is wrong with 104
something is wrong with 105
something is wrong with 105
something is wrong with 105
something is wrong with 105
something is wrong with 108
something is wrong with 108
something is wrong with 108
something is wrong with 108
something is wrong with 109
something is wrong with 109
something is wrong with 109
something is wrong with 109
something is wrong with 112
something is wrong with 112
something is wrong with 112
something is wrong with 112
something is wrong with 113
something is wrong with 113
something is wrong with 113
something is wrong w

In [6]:
red_boxes = []
for i in range(10):
    tmp = []
    tree = ET.parse('images_new_resized/green_new_labels/0000000'+str(i)+'.xml')
    root = tree.getroot()
    for child in root:
        if child.tag == 'object' :
            for subchild in child:
                if subchild.tag == 'bndbox':
                    for subsubchild in subchild:
                        if subsubchild.tag == 'xmin':
                            xmin = int(subsubchild.text)
                        elif subsubchild.tag == 'ymin':
                            ymin = int(subsubchild.text)
                        elif subsubchild.tag == 'xmax':
                            xmax = int(subsubchild.text)
                        elif subsubchild.tag == 'ymax':
                            ymax = int(subsubchild.text)
                    tmp.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    red_boxes.append(np.array(tmp))
    if len(red_boxes) == 0:
        print(i, "B A D")
        red_boxes.append([])
        
for i in range(10,100):
    try:
        tmp = []
        tree = ET.parse('images_new_resized/green_new_labels/000000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp.append(rectangle(xmin, ymin, xmax, ymax).toArray())
        red_boxes.append(np.array(tmp))
        if len(red_boxes) == 0:
            print(i, "B A D")
            red_boxes.append([])
    except:
        red_boxes.append([])
        
for i in range(100,500):
    try:
        tmp = []
        tree = ET.parse('images_new_resized/green_new_labels/00000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp.append(rectangle(xmin, ymin, xmax, ymax).toArray())
        red_boxes.append(np.array(tmp))
        if len(red_boxes) == 0:
            red_boxes.append([])
            print(i, "B A D")
    except:
        red_boxes.append([])
        
print(len(red_boxes))

500


In [5]:
boxes = green_boxes + red_boxes
print(len(boxes))

980


In [6]:
def remove_same(a, b):
    assert len(a) == len(b)
    for i in range(len(a)):
        try:
            if type(a[i]) != numpy.ndarray:
                a.pop(i)
                b.pop(i)
                remove_same(a,b)
        except:
            pass

In [7]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
greendata = []
for i in range(10):
    x = 'images_new_resized/green_new/0000000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x));
        assert cv2.imread(x).shape == (300,300,3)
        greendata.append(cv2.imread(x))
    except:
        greendata.append([])
for i in range(10,100):
    x = 'images_new_resized/green_new/000000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x)); 
        assert cv2.imread(x).shape == (300,300,3)
        greendata.append(cv2.imread(x))
    except:
         greendata.append([])
for i in range(100,480):
    x = 'images_new_resized/green_new/00000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x)); 
        assert cv2.imread(x).shape == (300,300,3)
        greendata.append(cv2.imread(x))
    except:
         greendata.append([])
greendata = np.array(greendata)

reddata = []
for i in range(10):
    x = 'images_new_resized/red_new/0000000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x));
        assert cv2.imread(x).shape == (300,300,3)
        reddata.append(cv2.imread(x))
    except:
        reddata.append([])
for i in range(10,100):
    x = 'images_new_resized/red_new/000000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x)); 
        assert cv2.imread(x).shape == (300,300,3)
        reddata.append(cv2.imread(x))
    except:
         reddata.append([])
for i in range(100,500):
    x = 'images_new_resized/red_new/00000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x)); 
        assert cv2.imread(x).shape == (300,300,3)
        reddata.append(cv2.imread(x))
    except:
         reddata.append([])


print(len(greendata))
print(len(reddata))

480
500


In [8]:
# print(type(greendata))
greendata = list(greendata)
remove_same(greendata, green_boxes)

reddata = list(reddata)
remove_same(reddata, red_boxes)

In [9]:
print(len(greendata))
print(len(green_boxes))

print(len(reddata))
print(len(red_boxes))

381
381
412
412
