In [2]:
import numpy as np

"""
Rectangle class that allows for easier use/access to the four coordinates of a bounding box
"""
class rectangle:
    def __init__(self, xmin, ymin, xmax, ymax):
        self.xmin = xmin
        self.ymin = ymin
        self.xmax = xmax
        self.ymax = ymax
    
    def __repr__(self):
        return str(np.array([self.xmin, self.ymin, self.xmax, self.ymax]))
    
    
    def toArray(self):
        return np.array([self.xmin, self.ymin, self.xmax, self.ymax])
    

In [3]:
dataset = []
import xml.etree.ElementTree as ET
a = []
green = []
red = []
xmin = 0
ymin = 0
xmax = 0
ymax = 0
tree = ET.parse('images_new_resized/green_new_labels/00000007.xml')
root = tree.getroot()
for child in root:
    if child.tag == 'object' :
        for subchild in child:
            if subchild.tag == 'bndbox':
                for subsubchild in subchild:
                    if subsubchild.tag == 'xmin':
                        xmin = int(subsubchild.text)
                    elif subsubchild.tag == 'ymin':
                        ymin = int(subsubchild.text)
                    elif subsubchild.tag == 'xmax':
                        xmax = int(subsubchild.text)
                    elif subsubchild.tag == 'ymax':
                        ymax = int(subsubchild.text)
                a.append(rectangle(xmin, ymin, xmax, ymax).toArray())


                
for l in range(len(a)):
    a[l] = np.array(a[l])
print(np.array(a))

[[128  64 173 132]
 [ 10 207  53 274]
 [ 59 209  96 278]
 [103 211 134 274]
 [142 212 173 272]
 [183 210 210 276]
 [217 214 247 278]
 [254 213 287 280]]


In [12]:
boxes = []
for i in range(10):
    tmp = []
    tree = ET.parse('images_new_resized/green_new_labels/0000000'+str(i)+'.xml')
    root = tree.getroot()
    for child in root:
        if child.tag == 'object' :
            for subchild in child:
                if subchild.tag == 'bndbox':
                    for subsubchild in subchild:
                        if subsubchild.tag == 'xmin':
                            xmin = int(subsubchild.text)
                        elif subsubchild.tag == 'ymin':
                            ymin = int(subsubchild.text)
                        elif subsubchild.tag == 'xmax':
                            xmax = int(subsubchild.text)
                        elif subsubchild.tag == 'ymax':
                            ymax = int(subsubchild.text)
                    tmp.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    boxes.append(np.array(tmp))
    if len(boxes) == 0:
        boxes.append([])
        
for i in range(10,100):
    try:
        tmp = []
        tree = ET.parse('images_new_resized/green_new_labels/000000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp.append(rectangle(xmin, ymin, xmax, ymax).toArray())
        boxes.append(np.array(tmp))
        if len(boxes) == 0:
            boxes.append([])
    except:
        boxes.append([])
        
for i in range(100,480):
    try:
        tmp = []
        tree = ET.parse('images_new_resized/green_new_labels/00000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp.append(rectangle(xmin, ymin, xmax, ymax).toArray())
        boxes.append(np.array(tmp))
        if len(boxes) == 0:
            boxes.append([])
            print(i, "B A D")
    except:
        boxes.append([])
        
for box_set in boxes:
    print(box_set)


[[117 126 160 176]]
[[ 50  44 256 266]]
[[ 73  22 279 261]]
[[112 103 178 203]]
[[ 96 123 163 184]]
[[169 132 230 193]]
[[114  96 203 241]]
[[128  64 173 132]
 [ 10 207  53 274]
 [ 59 209  96 278]
 [103 211 134 274]
 [142 212 173 272]
 [183 210 210 276]
 [217 214 247 278]
 [254 213 287 280]]
[[172  41 270 230]]
[[ 95  82 165 239]]
[[ 30 178  76 239]]
[[100  84 191 220]]
[[147 145 227 203]]
[[145 106 185 200]]
[[ 83 152 178 246]]
[[179 166 239 260]]
[]
[]
[]
[[117 138 166 195]]
[]
[[143 146 174 193]]
[[224 121 262 196]]
[[ 39  15 283 271]]
[[100  63 181 166]]
[[ 91  91 226 220]]
[[159  57 184  90]]
[[113 120 188 185]]
[]
[[ 52  14 275 227]]
[[ 40 159  97 237]]
[[100  89 162 199]]
[[115 118 155 181]]
[[115 204 190 272]]
[]
[[149 120 212 188]]
[[105  69 200 224]]
[[106  96 281 278]]
[[116 118 150 173]]
[[151 158 171 201]]
[]
[[ 88 106 203 196]]
[[146 102 247 221]]
[[ 94 195 167 257]]
[]
[[118  79 188 263]]
[]
[[103  82 184 159]]
[[145  85 236 266]]
[[ 74 156 111 225]]
[]
[[125 157 176 230

[array([[117, 126, 160, 176]]), array([[ 50,  44, 256, 266]]), array([[ 73,  22, 279, 261]]), array([[112, 103, 178, 203]]), array([[ 96, 123, 163, 184]]), array([[169, 132, 230, 193]]), array([[114,  96, 203, 241]]), array([[128,  64, 173, 132],
       [ 10, 207,  53, 274],
       [ 59, 209,  96, 278],
       [103, 211, 134, 274],
       [142, 212, 173, 272],
       [183, 210, 210, 276],
       [217, 214, 247, 278],
       [254, 213, 287, 280]]), array([[172,  41, 270, 230]]), array([[ 95,  82, 165, 239]]), array([[ 30, 178,  76, 239]]), array([[100,  84, 191, 220]]), array([[147, 145, 227, 203]]), array([[145, 106, 185, 200]]), array([[ 83, 152, 178, 246]]), array([[179, 166, 239, 260]]), [], [], [], array([[117, 138, 166, 195]]), [], array([[143, 146, 174, 193]]), array([[224, 121, 262, 196]]), array([[ 39,  15, 283, 271]]), array([[100,  63, 181, 166]]), array([[ 91,  91, 226, 220]]), array([[159,  57, 184,  90]]), array([[113, 120, 188, 185]]), [], array([[ 52,  14, 275, 227]]), a

In [18]:
def remove_same(a, b):
    assert len(a) == len(b)
    for i in range(len(a)):
        try:
            if a[i] == []:
                a.pop(i)
                b.pop(i)
                remove_same(a,b)
        except:
            pass

[1, 2, 3, 4, 5]
[1, 2, 4, 3, 9]


[1, 2, 3, 4, 5, 6]