In [1]:
import numpy as np
import numpy

"""
Rectangle class that allows for easier use/access to the four coordinates of a bounding box
"""
class rectangle:
    def __init__(self, xmin, ymin, xmax, ymax):
        self.xmin = xmin
        self.ymin = ymin
        self.xmax = xmax
        self.ymax = ymax
    
    def __repr__(self):
        return str(np.array([self.xmin, self.ymin, self.xmax, self.ymax]))
    
    
    def toArray(self):
        return np.array([self.xmin, self.ymin, self.xmax, self.ymax])


In [2]:
"""
Just testing stuff
"""
dataset = []
import xml.etree.ElementTree as ET
a = []
green = []
red = []
xmin = 0
ymin = 0
xmax = 0
ymax = 0
tree = ET.parse('images_new_resized/green_new_labels/00000007.xml')
root = tree.getroot()
for child in root:
    if child.tag == 'object' :
        for subchild in child:
            if subchild.tag == 'bndbox':
                for subsubchild in subchild:
                    if subsubchild.tag == 'xmin':
                        xmin = int(subsubchild.text)
                    elif subsubchild.tag == 'ymin':
                        ymin = int(subsubchild.text)
                    elif subsubchild.tag == 'xmax':
                        xmax = int(subsubchild.text)
                    elif subsubchild.tag == 'ymax':
                        ymax = int(subsubchild.text)
                a.append(rectangle(xmin, ymin, xmax, ymax).toArray())


                
for l in range(len(a)):
    a[l] = np.array(a[l])
print(np.array(a))

[[128  64 173 132]
 [ 10 207  53 274]
 [ 59 209  96 278]
 [103 211 134 274]
 [142 212 173 272]
 [183 210 210 276]
 [217 214 247 278]
 [254 213 287 280]]


In [3]:
boxes = []
colors = []
for i in range(10):
    tmp_box = []
    tmp_color = []
    try:
        tree = ET.parse('images_new_resized/green_new_labels/0000000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_color.append(0)
                        elif subchild.text == 'red':
                            tmp_color.append(1)
                        else:
                            print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp_box.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    except:
        boxes.append([])
        colors.append([])
        continue

    boxes.append(tmp_box)
    colors.append(tmp_color)
        
for i in range(10,100):
    tmp_box = []
    tmp_color = []
    try:
        tree = ET.parse('images_new_resized/green_new_labels/000000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_color.append(0)
                        elif subchild.text == 'red':
                            tmp_color.append(1)
                        else:
                            print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp_box.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    except:
        boxes.append([])
        colors.append([])
        continue

    boxes.append(tmp_box)
    colors.append(tmp_color)
    
    
for i in range(100,480):
    tmp_box = []
    tmp_color = []
    try:
        tree = ET.parse('images_new_resized/green_new_labels/00000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_color.append(0)
                        elif subchild.text == 'red':
                            tmp_color.append(1)
                        else:
                            print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp_box.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    except:
        boxes.append([])
        colors.append([])
        continue

    boxes.append(tmp_box)
    colors.append(tmp_color)
print(len(colors))
print(len(boxes))

480
480


In [4]:
for i in range(10):
    tmp_box = []
    tmp_color = []
    try:
        tree = ET.parse('images_new_resized/red_new_labels/0000000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_color.append(0)
                        elif subchild.text == 'red':
                            tmp_color.append(1)
                        else:
                            print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp_box.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    except:
        boxes.append([])
        colors.append([])
        continue

    boxes.append(tmp_box)
    colors.append(tmp_color)
        
for i in range(10,100):
    tmp_box = []
    tmp_color = []
    try:
        tree = ET.parse('images_new_resized/red_new_labels/000000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_color.append(0)
                        elif subchild.text == 'red':
                            tmp_color.append(1)
                        else:
                            print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp_box.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    except:
        boxes.append([])
        colors.append([])
        continue

    boxes.append(tmp_box)
    colors.append(tmp_color)
    
    
for i in range(100,500):
    tmp_box = []
    tmp_color = []
    try:
        tree = ET.parse('images_new_resized/red_new_labels/00000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_color.append(0)
                        elif subchild.text == 'red':
                            tmp_color.append(1)
                        else:
                            print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp_box.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    except:
        boxes.append([])
        colors.append([])
        continue
    boxes.append(tmp_box)
    colors.append(tmp_color)
        
print(len(boxes))
print(len(colors))

980
980


In [5]:
def remove_same(a, b, c):
    assert len(a) == len(b) and len(b) == len(c)
    for i in range(len(a)):
        try:
            if type(a[i]) != numpy.ndarray:
                a.pop(i)
                b.pop(i)
                c.pop(i)
                remove_same(a,b,c)
        except:
            pass

In [6]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
images = []
for i in range(10):
    x = 'images_new_resized/green_new/0000000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x));
        assert cv2.imread(x).shape == (300,300,3)
        images.append(cv2.imread(x))
    except:
        images.append([])
for i in range(10,100):
    x = 'images_new_resized/green_new/000000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x)); 
        assert cv2.imread(x).shape == (300,300,3)
        images.append(cv2.imread(x))
    except:
         images.append([])
for i in range(100,480):
    x = 'images_new_resized/green_new/00000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x)); 
        assert cv2.imread(x).shape == (300,300,3)
        images.append(cv2.imread(x))
    except:
         images.append([])


for i in range(10):
    x = 'images_new_resized/red_new/0000000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x));
        assert cv2.imread(x).shape == (300,300,3)
        images.append(cv2.imread(x))
    except:
        images.append([])
for i in range(10,100):
    x = 'images_new_resized/red_new/000000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x)); 
        assert cv2.imread(x).shape == (300,300,3)
        images.append(cv2.imread(x))
    except:
         images.append([])
for i in range(100,500):
    x = 'images_new_resized/red_new/00000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x)); 
        assert cv2.imread(x).shape == (300,300,3)
        images.append(cv2.imread(x))
    except:
         images.append([])

images = np.array(images)

In [7]:
len(images)

980

In [8]:
print(len(images), len(boxes), len(colors))

980 980 980


In [9]:
images = list(images)
boxes = list(boxes)
colors = list(colors)
remove_same(images, boxes, colors)

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out o

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out o

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out o

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out o

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out o

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out o

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out o

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out o

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out o

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out o

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out o

In [10]:
print(len(images), len(boxes), len(colors))

793 793 793


In [15]:
def bgr_to_rgb(img):
    return img[:, :, ::-1]