In [1]:
import numpy as np
import numpy

"""
Rectangle class that allows for easier use/access to the four coordinates of a bounding box
"""
class rectangle:
    def __init__(self, xmin, ymin, xmax, ymax):
        self.xmin = xmin
        self.ymin = ymin
        self.xmax = xmax
        self.ymax = ymax
    
    def __repr__(self):
        return str(np.array([self.xmin, self.ymin, self.xmax, self.ymax]))
    
    
    def toArray(self):
        return np.array([self.xmin, self.ymin, self.xmax, self.ymax])


In [2]:
"""
Just testing stuff
"""
dataset = []
import xml.etree.ElementTree as ET
a = []
green = []
red = []
xmin = 0
ymin = 0
xmax = 0
ymax = 0
tree = ET.parse('images_new_resized/green_new_labels/00000007.xml')
root = tree.getroot()
for child in root:
    if child.tag == 'object' :
        for subchild in child:
            if subchild.tag == 'bndbox':
                for subsubchild in subchild:
                    if subsubchild.tag == 'xmin':
                        xmin = int(subsubchild.text)
                    elif subsubchild.tag == 'ymin':
                        ymin = int(subsubchild.text)
                    elif subsubchild.tag == 'xmax':
                        xmax = int(subsubchild.text)
                    elif subsubchild.tag == 'ymax':
                        ymax = int(subsubchild.text)
                a.append(rectangle(xmin, ymin, xmax, ymax).toArray())


                
for l in range(len(a)):
    a[l] = np.array(a[l])
print(np.array(a))

[[128  64 173 132]
 [ 10 207  53 274]
 [ 59 209  96 278]
 [103 211 134 274]
 [142 212 173 272]
 [183 210 210 276]
 [217 214 247 278]
 [254 213 287 280]]


In [3]:
boxes = []
colors = []
for i in range(10):
    tmp_box = []
    tmp_color = []
    try:
        tree = ET.parse('images_new_resized/green_new_labels/0000000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_color.append(0)
                        elif subchild.text == 'red':
                            tmp_color.append(1)
                        else:
                            print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp_box.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    except:
        boxes.append([])
        colors.append([])
        continue

    boxes.append(tmp_box)
    colors.append(tmp_color)
        
for i in range(10,100):
    tmp_box = []
    tmp_color = []
    try:
        tree = ET.parse('images_new_resized/green_new_labels/000000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_color.append(0)
                        elif subchild.text == 'red':
                            tmp_color.append(1)
                        else:
                            print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp_box.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    except:
        boxes.append([])
        colors.append([])
        continue

    boxes.append(tmp_box)
    colors.append(tmp_color)
    
    
for i in range(100,480):
    tmp_box = []
    tmp_color = []
    try:
        tree = ET.parse('images_new_resized/green_new_labels/00000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_color.append(0)
                        elif subchild.text == 'red':
                            tmp_color.append(1)
                        else:
                            print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp_box.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    except:
        boxes.append([])
        colors.append([])
        continue

    boxes.append(tmp_box)
    colors.append(tmp_color)
print(len(colors))
print(len(boxes))

480
480


In [4]:
for i in range(10):
    tmp_box = []
    tmp_color = []
    try:
        tree = ET.parse('images_new_resized/red_new_labels/0000000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_color.append(0)
                        elif subchild.text == 'red':
                            tmp_color.append(1)
                        else:
                            print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp_box.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    except:
        boxes.append([])
        colors.append([])
        continue

    boxes.append(tmp_box)
    colors.append(tmp_color)
        
for i in range(10,100):
    tmp_box = []
    tmp_color = []
    try:
        tree = ET.parse('images_new_resized/red_new_labels/000000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_color.append(0)
                        elif subchild.text == 'red':
                            tmp_color.append(1)
                        else:
                            print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp_box.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    except:
        boxes.append([])
        colors.append([])
        continue

    boxes.append(tmp_box)
    colors.append(tmp_color)
    
    
for i in range(100,500):
    tmp_box = []
    tmp_color = []
    try:
        tree = ET.parse('images_new_resized/red_new_labels/00000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'name':
                        if subchild.text == 'green':
                            tmp_color.append(0)
                        elif subchild.text == 'red':
                            tmp_color.append(1)
                        else:
                            print("something is wrong with "+str(i))
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp_box.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    except:
        boxes.append([])
        colors.append([])
        continue
    boxes.append(tmp_box)
    colors.append(tmp_color)
        
print(len(boxes))
print(len(colors))

980
980


In [5]:
def remove_same(a, b, c):
    assert len(a) == len(b) and len(b) == len(c)
    for i in range(len(a)):
        try:
            if type(a[i]) != numpy.ndarray:
                a.pop(i)
                b.pop(i)
                c.pop(i)
                remove_same(a,b,c)
        except:
            pass

In [6]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
images = []
for i in range(10):
    x = 'images_new_resized/green_new/0000000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x));
        assert cv2.imread(x).shape == (300,300,3)
        images.append(cv2.imread(x))
    except:
        images.append([])
for i in range(10,100):
    x = 'images_new_resized/green_new/000000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x)); 
        assert cv2.imread(x).shape == (300,300,3)
        images.append(cv2.imread(x))
    except:
         images.append([])
for i in range(100,480):
    x = 'images_new_resized/green_new/00000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x)); 
        assert cv2.imread(x).shape == (300,300,3)
        images.append(cv2.imread(x))
    except:
         images.append([])


for i in range(10):
    x = 'images_new_resized/red_new/0000000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x));
        assert cv2.imread(x).shape == (300,300,3)
        images.append(cv2.imread(x))
    except:
        images.append([])
for i in range(10,100):
    x = 'images_new_resized/red_new/000000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x)); 
        assert cv2.imread(x).shape == (300,300,3)
        images.append(cv2.imread(x))
    except:
         images.append([])
for i in range(100,500):
    x = 'images_new_resized/red_new/00000'+str(i)+".jpg"
    try:
        plt.imshow(cv2.imread(x)); 
        assert cv2.imread(x).shape == (300,300,3)
        images.append(cv2.imread(x))
    except:
         images.append([])

images = np.array(images)

In [7]:
len(images)

980

In [8]:
print(len(images), len(boxes), len(colors))

980 980 980


In [9]:
images = list(images)
boxes = list(boxes)
colors = list(colors)
remove_same(images, boxes, colors)

In [10]:
print(len(images), len(boxes), len(colors))

793 793 793


In [11]:
def bgr_to_rgb(img):
    return img[:, :, ::-1]

In [12]:
images = np.array(images)
boxes = np.array(boxes)
colors = np.array(colors)

The following code was created using [https://github.com/CogWorksBWSI/detection/](https://github.com/CogWorksBWSI/detection/) as a reference for creating a pytorch object detection model

In [13]:
from pathlib import Path

import numba
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
%matplotlib notebook

import torch
from torch import nn
import torch.nn.functional as F

In [14]:
images = np.array(images)
images = images.reshape(-1,3,300,300)
images.shape

(793, 3, 300, 300)

In [15]:
anchor_boxes = []
for y in range(0, images.shape[2], 15):
    for x in range(0, images.shape[3], 15):
        anchor_boxes.append(np.array([-15, -15, 15, 15]) + np.array([x, y, x, y]))
anchor_boxes = np.vstack(anchor_boxes)

In [16]:
# @numba.njit
def compute_iou(boxes, truth):
    N = boxes.shape[0]
    K = truth.shape[0]
    ious = np.zeros((N, K), dtype=np.float32)

    for k in range(K):
        truth_area = (truth[k, 2] - truth[k, 0]) * (truth[k, 3] - truth[k, 1])
        for n in range(N):
            width_overlap = min(boxes[n, 2], truth[k, 2]) - max(boxes[n, 0], truth[k, 0])
            if width_overlap > 0:
                height_overlap = min(boxes[n, 3], truth[k, 3]) - max(boxes[n, 1], truth[k, 1])
                if height_overlap > 0:
                    union = (boxes[n, 2] - boxes[n, 0]) * (boxes[n, 3] - boxes[n, 1]) + truth_area - (width_overlap * height_overlap)
                    ious[n, k] = width_overlap * height_overlap / union
    return ious

In [17]:
def box_overlaps(
        predicted,
        truth,
        eps: float = 1e-12,
):
    """ Return the overlap between two lists of boxes.
    Calculates the intersection over union between a list of predicted boxes
    and a list of ground-truth boxes.
    Parameters
    ----------
    boxes : numpy.ndarray, shape=(N, 4)
        The predicted boxes, in xyxy format.
    truth : numpy.ndarray, shape=(K, 4)
        The ground-truth boxes, in xyxy format.
    eps : Real, optional (default=1e-12)
        The epsilon value to apply to the intersection over union computation for stability.
    Returns
    -------
    numpy.ndarray, shape=(N, K)
        The overlap between the predicted and ground-truth boxes
    Notes
    -----
    The format referred to, xyxy format, indicates (left, top, right, bottom) in pixel space.
    Examples
    --------
    >>> from detection_utils.boxes import box_overlaps
    >>> import numpy as np
    >>> predicted_boxes = np.array([[0, 0, 10, 10], # left, top, right, bottom (xyxy) format
    ...                             [3, 3,  7,  7]])
    >>> true_boxes = np.array([[2, 3, 6, 7]])
    >>> box_overlaps(predicted_boxes, true_boxes)
    array([[0.16], [0.6])
    """
    N = predicted.shape[0]
    K = truth.shape[0]
    ious = np.zeros((N, K), dtype=np.float32)

    for k in range(K):
        truth_area = (truth[k, 2] - truth[k, 0]) * (truth[k, 3] - truth[k, 1])
        for n in range(N):
            width_overlap = min(predicted[n, 2], truth[k, 2]) - max(predicted[n, 0], truth[k, 0])
            if width_overlap > 0:
                height_overlap = min(predicted[n, 3], truth[k, 3]) - max(predicted[n, 1], truth[k, 1])
                if height_overlap > 0:
                    overlap_area = width_overlap * height_overlap
                    box_area = (predicted[n, 2] - predicted[n, 0]) * (predicted[n, 3] - predicted[n, 1])
                    union = box_area + truth_area - overlap_area
                    ious[n, k] = overlap_area / (union + eps)
    return ious

In [18]:
def generate_targets(
        anchor_boxes,
        truth_boxes,
        labels,
        pos_thresh: float = 0.3,
        neg_thresh: float = 0.2,
        eps: float = 1e-12,):
    """ Generate classification and regression targets from ground-truth boxes.
    Each regression target is matched to its highest-overlapping ground-truth box. Those
    targets with less than a `pos_thresh` IoU are marked as background. Targets with
    `neg_thresh` <= IoU < `pos_thresh` are flagged as ignore boxes. Boxes are regressed
    based on their centers and widths/heights.
    Parameters
    ----------
    anchor_boxes : numpy.ndarray, shape=(N, 4)
        Anchor boxes in xyxy format.
    truth_boxes : numpy.ndarray, shape=(K, 4)
        Ground-truth boxes in xyxy format.
    labels : numpy.ndarray, shape=(K,)
        The labels associated with each ground-truth box.
    pos_thresh : Real
        The minimum overlap threshold between a truth and anchor box for that truth box to
        be 'responsible' for detecting the anchor.
    neg_thresh : Real
        The maximum overlap threshold between a truth and anchor box for that anchor box to
        be called a negative. Those anchor boxes with overlap greater than this but less than
        `pos_thresh` will be marked as ignored.
    eps : Real, optional (default=1e-12)
        The epsilon to use for numerical stability.
    Returns
    -------
    Tuple[numpy.ndarray shape=(N,), numpy.ndarray shape=(N, 4)]
        The classification and bounding box regression targets for each anchor box. Regressions
        are of format (x-center, y-center, width, height). Classification targets of 0 indicate
        background, while targets of -1 indicate that this prediction should be ignored as a
        difficult case.
    Examples
    --------
    >>> from detection_utils.boxes import generate_targets
    >>> import numpy as np
    >>> anchors = np.array([[-0.5,   -0.5,   0.5,   0.5],
    ...                     [ 0.0,   -0.5,   1.0,   1.5],
    ...                     [ 0.5,    0.0,   1.5,   1.0]])
    >>> targets = np.array([[0, 0, 1, 1]])
    >>> labels = np.array([1])
    >>> generate_targets(anchors, targets, labels)
    (array([0, 1]),
     array([[ 5.000000e-01,  5.000000e-01, -1.110223e-16, -1.110223e-16],
        [ 0.000000e+00,  0.000000e+00, -1.110223e-16, -6.931472e-01],
        [-5.000000e-01,  0.000000e+00, -1.110223e-16, -1.110223e-16]]))
    """
    if truth_boxes.size == 0:
        targets_reg = np.zeros_like(anchor_boxes, dtype=np.float32)
        targets_cls = np.zeros(anchor_boxes.shape[0], dtype=np.int64)
        return targets_cls, targets_reg

    ious = box_overlaps(anchor_boxes, truth_boxes)  # NxK
    max_ious = ious.max(axis=1)                     # N IoUs
    max_idxs = ious.argmax(axis=1)                  # N indices

    target_boxes = truth_boxes[max_idxs]

    target_centers = (target_boxes[:, :2] + target_boxes[:, 2:]) / 2
    anchor_centers = (anchor_boxes[:, :2] + anchor_boxes[:, 2:]) / 2
    target_wh = target_boxes[:, 2:] - target_boxes[:, :2]
    anchor_wh = anchor_boxes[:, 2:] - anchor_boxes[:, :2]

    xy = (target_centers - anchor_centers) / anchor_wh
    wh = np.log(target_wh / (anchor_wh + eps) + eps)

    targets_reg = np.hstack([xy, wh])
    targets_cls = labels[max_idxs]
    targets_cls[max_ious < pos_thresh] = -1
    targets_cls[max_ious < neg_thresh] = 0

    targets_cls = targets_cls.reshape(-1).astype(np.int32)
    targets_reg = targets_reg.reshape(-1, 4).astype(np.float32)

    return targets_cls, targets_reg


In [19]:
def add_detection(ax, box, label):
    x, y, x2, y2 = box
    w = x2 - x
    h = y2 - y
    ax.add_patch(Rectangle((x, y), w, h, color='r', lw=2, fill=None))
    label = int(label)
    label = 'rectangle' if label == 1 else label
    label = 'triangle' if label == 2 else label
    label = 'circle' if label == 3 else label
    ax.annotate(label, (x, y))

In [20]:
def non_max_suppression(detections, threshold=0.7):
    x1s = detections[:, 0]
    y1s = detections[:, 1]
    x2s = detections[:, 2]
    y2s = detections[:, 3]

    areas = (x2s - x1s) * (y2s - y1s)
    order = detections[:, 4].argsort()[::-1] # highest to lowest score

    keep = [] # which detections are we going to keep?
    while order.size > 0:
        i = order[0]
        keep.append(i)
        all_others = order[1:] # everything except the current box
        width_overlaps = np.maximum(0, np.minimum(x2s[i], x2s[all_others])  -
                                       np.maximum(x1s[i], x1s[all_others]))
        height_overlaps = np.maximum(0, np.minimum(y2s[i], y2s[all_others]) - 
                                        np.maximum(y1s[i], y1s[all_others]))
        intersections = width_overlaps * height_overlaps
        ious = intersections / (areas[i] + areas[all_others] - intersections)

        # +1 to counteract the offset all_others = order[1:]
        order = order[np.where(ious <= threshold)[0] + 1]

    return keep

In [21]:
def compute_recall(prediction_detections, truth_detections, threshold=0.5):
    ious = compute_iou(prediction_detections[:, :4], truth_detections[:, :4])
    max_ious = ious.max(axis=1) # N IoUs
    max_idxs = ious.argmax(axis=1)
    
    predictions = prediction_detections[:, -1]
    truths = truth_detections[:, -1]
    target_labels = truths[max_idxs]
    correct = predictions == target_labels
    true_pos = correct[np.logical_and(max_ious >= threshold, target_labels > 0)].sum()
    
    wrong = predictions != target_labels
    false_negatives = wrong[np.logical_and(max_ious >= threshold, predictions == 0)].sum()
    false_negatives += (ious.max(axis=0) < threshold).sum()
    if true_pos + false_negatives == 0:
        return 1
    return true_pos / (true_pos + false_negatives)

In [22]:
def compute_precision(prediction_detections, truth_detections, threshold=0.5):
    ious = compute_iou(prediction_detections[:, :4], truth_detections[:, :4])
    max_ious = ious.max(axis=1)
    max_idxs = ious.argmax(axis=1)
    
    predictions = prediction_detections[:, -1]
    truths = truth_detections[:, -1]
    target_labels = truths[max_idxs]

    correct = predictions == target_labels
    true_pos = correct[np.logical_and(max_ious >= threshold, target_labels > 0)].sum()
    total_preds = (predictions > 0).sum()
    return true_pos / total_preds if total_preds > 0 else 0

In [23]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 10, 3, padding=1)
        self.conv2 = nn.Conv2d(10, 20, 3, padding=1)
        self.conv3 = nn.Conv2d(20, 30, 3, padding=1)
        self.conv4 = nn.Conv2d(30, 40, 3, padding=1)
        
        self.classification = nn.Conv2d(40, 4, 1) # background/rectangle/square/circle
        self.regression = nn.Conv2d(40, 4, 1)
        
        for layer in (self.conv1, self.conv2, self.conv3, self.conv4,
                     self.classification, self.regression):
            nn.init.xavier_normal_(layer.weight, np.sqrt(2))
            nn.init.constant_(layer.bias, 0)

        nn.init.constant_(self.classification.bias[0], 10)
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), 2)
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = F.max_pool2d(F.relu(self.conv3(x)), 2)
        x = F.max_pool2d(F.relu(self.conv4(x)), 2)
        
        classification = self.classification(x)
        regressions = self.regression(x)
        
        return classification, regressions

In [24]:
def forward_data(data):
    classifications, regressions = model(torch.tensor(data).to(device))
    classifications = classifications.permute(0, 2, 3, 1).reshape(-1, 4)
    regressions = regressions.permute(0, 2, 3, 1).reshape(-1, 4)
    return classifications, regressions

In [25]:
def compute_detections(classifications, regressions):
    scores = F.softmax(classifications, dim=-1).detach().cpu().numpy()
    scores = 1 - scores[:, 0] # foreground score for NMS
    
    classifications = classifications.argmax(dim=-1).detach().cpu().numpy()
    regressions = regressions.detach().cpu().numpy()
    detections = []
    for i in range(len(classifications)):
        y, x = i // 16 * 16, (i % 16) * 16
        x_reg, y_reg, w_reg, h_reg = regressions[i]
        x += x_reg * 32
        y += y_reg * 32
        w = np.exp(w_reg) * 32
        h = np.exp(h_reg) * 32
        detections.append((x - w/2, y - h/2, x + w/2, y + h/2, scores[i], classifications[i]))
    return np.array(detections)

In [26]:
def compute_ar(classifications, regressions, boxes, labels, nms_threshold=0.3, 
                ar_threshold=0.5):
    detections = compute_detections(classifications, regressions)
    detections = detections[non_max_suppression(detections[:, :5], nms_threshold)]
    detections = np.hstack((detections[:, :4], detections[:, -1:])) # remove score; keep label
    
    truth_detections = np.hstack((boxes, labels))
    if len(detections) > 0:
        return compute_recall(detections, truth_detections, ar_threshold)
    return 0

In [27]:
def compute_ap(classifications, regressions, boxes, labels, nms_threshold=0.3, 
                ap_threshold=0.5):
    detections = compute_detections(classifications, regressions)
    detections = detections[non_max_suppression(detections[:, :5], nms_threshold)]
    detections = np.hstack((detections[:, :4], detections[:, -1:])) # remove score; keep label
    
    truth_detections = np.hstack((boxes, labels))
    if len(detections) > 0:
        return compute_precision(detections, truth_detections, ap_threshold)
    return 0

In [28]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

def softmax_focal_loss(inputs, targets, alpha=1, gamma=0):
    inputs = F.softmax(inputs, dim=1)
    pc = inputs[(range(len(targets)), targets)]
    return -torch.mean(alpha * (1 - pc)**gamma * torch.log(pc + 1e-08))

images = torch.tensor(images).to(device)


In [29]:
images = images.float()
print(images)

tensor([[[[233., 170., 120.,  ..., 232., 167., 116.],
          [232., 167., 116.,  ..., 234., 169., 118.],
          [234., 169., 118.,  ..., 236., 177., 132.],
          ...,
          [208., 153., 108.,  ..., 246., 189., 137.],
          [242., 191., 135.,  ..., 244., 200., 159.],
          [239., 195., 154.,  ..., 240., 224., 208.]],

         [[172., 117.,  72.,  ..., 243., 189., 136.],
          [241., 190., 134.,  ..., 246., 202., 161.],
          [240., 197., 158.,  ..., 240., 224., 208.],
          ...,
          [190., 242., 249.,  ..., 173., 221., 255.],
          [165., 214., 246.,  ...,  85., 145., 167.],
          [ 76., 128., 151.,  ..., 130., 138., 107.]],

         [[172., 222., 228.,  ..., 148., 199., 231.],
          [146., 198., 228.,  ..., 114., 167., 180.],
          [160., 203., 218.,  ..., 140., 151., 125.],
          ...,
          [ 57., 182., 243.,  ...,   2., 138., 202.],
          [ 17., 160., 227.,  ...,  17., 187., 241.],
          [  1., 179., 236.,  ...

In [30]:
images /= 255
print(images[0])

tensor([[[0.9137, 0.6667, 0.4706,  ..., 0.9098, 0.6549, 0.4549],
         [0.9098, 0.6549, 0.4549,  ..., 0.9176, 0.6627, 0.4627],
         [0.9176, 0.6627, 0.4627,  ..., 0.9255, 0.6941, 0.5176],
         ...,
         [0.8157, 0.6000, 0.4235,  ..., 0.9647, 0.7412, 0.5373],
         [0.9490, 0.7490, 0.5294,  ..., 0.9569, 0.7843, 0.6235],
         [0.9373, 0.7647, 0.6039,  ..., 0.9412, 0.8784, 0.8157]],

        [[0.6745, 0.4588, 0.2824,  ..., 0.9529, 0.7412, 0.5333],
         [0.9451, 0.7451, 0.5255,  ..., 0.9647, 0.7922, 0.6314],
         [0.9412, 0.7725, 0.6196,  ..., 0.9412, 0.8784, 0.8157],
         ...,
         [0.7451, 0.9490, 0.9765,  ..., 0.6784, 0.8667, 1.0000],
         [0.6471, 0.8392, 0.9647,  ..., 0.3333, 0.5686, 0.6549],
         [0.2980, 0.5020, 0.5922,  ..., 0.5098, 0.5412, 0.4196]],

        [[0.6745, 0.8706, 0.8941,  ..., 0.5804, 0.7804, 0.9059],
         [0.5725, 0.7765, 0.8941,  ..., 0.4471, 0.6549, 0.7059],
         [0.6275, 0.7961, 0.8549,  ..., 0.5490, 0.5922, 0.

In [31]:
print(images.shape)
for i in range(len(boxes)):
    boxes[i] = np.array(boxes[i])
for i in range(len(colors)):
    colors[i] = np.array(colors[i])


torch.Size([793, 3, 300, 300])


In [41]:
for i in range(100):
    print(boxes[i].shape)

(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(8, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(0,)
(0,)
(1, 4)
(0,)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(0,)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(0,)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(0,)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(0,)
(1, 4)
(0,)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(3, 4)
(1, 4)
(1, 4)
(1, 4)
(4, 4)
(1, 4)
(1, 4)
(1, 4)
(0,)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(2, 4)
(0,)
(1, 4)
(0,)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(0,)
(1, 4)
(1, 4)
(0,)
(2, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(1, 4)
(2, 4)
(2, 4)
(1, 4)
(1, 4)
(0,)
(0,)
(1, 4)
(0,)


In [33]:
 def train_epoch():
    torch.set_grad_enabled(True)
    idxs = np.arange(len(images))
    np.random.shuffle(idxs)
    
    for idx in idxs:
        img, Tboxes, labels = images[idx], boxes[idx], colors[idx]
    
        cls_targs, reg_targs = generate_targets(anchor_boxes, Tboxes, labels)
        classifications, regressions = forward_data(img[np.newaxis])
        
        print(f"Tboxes shape: {Tboxes.shape}")
        print(f"Targer Shape: {reg_targs.shape}")

        mask = np.where(cls_targs > -1)[0]
        cls_loss = softmax_focal_loss(classifications[mask].cpu(), cls_targs[mask], 
                                      alpha=0.25, gamma=2)
        
        mask = np.where(cls_targs > 0)[0]
        reg_loss = F.smooth_l1_loss(regressions[mask].cpu(), reg_targs[mask])
        
        total_loss = cls_loss + reg_loss
        total_loss.backward()
        optim.step()
        optim.zero_grad()
    

        ap = compute_ap(classifications, regressions, Tboxes, labels[:, np.newaxis])
        ar = compute_ar(classifications, regressions, Tboxes, labels[:, np.newaxis])
        
        plotter.set_train_batch({'loss': total_loss.item(),
                                 'reg_loss': reg_loss.item(),
                                 'cls_loss': cls_loss.item(),
                                 'Precision': ap, 
                                 'Recall': ar}, 1)

#     for idx in range(len(val_data““““
#         img, boxes, labels = val_data[idx], val_boxes[idx], val_labels[idx]
#         cls_targs, reg_targs = generate_targets(anchor_boxes, boxes, labels)
#         classifications, regressions = forward_data(img[np.newaxis])
        
#         mask = np.where(cls_targs > -1)[0]
#         cls_loss = softmax_focal_loss(classifications[mask].cpu(), cls_targs[mask], 
#                                       alpha=0.25, gamma=2)
#         mask = np.where(cls_targs > 0)[0]
#         reg_loss = F.smooth_l1_loss(regressions[mask].cpu(), reg_targs[mask])
#         total_loss = cls_loss + reg_loss
        
#         ap = compute_ap(classifications, regressions, boxes, labels[:, np.newaxis])
#         ar = compute_ar(classifications, regressions, boxes, labels[:, np.newaxis])
#         plotter.set_test_batch({'loss': total_loss.item(),
#                                  'reg_loss': reg_loss.item(),
#                                  'cls_loss': cls_loss.item(),
#                                  'Precision': ap,
#                                  'Recall': ar}, 1)
        
    plotter.set_train_epoch()
#     plotter.plot_test_epoch()

In [34]:
%matplotlib notebook
from noggin import create_plot
model = Model().to(device)

optim = torch.optim.Adam(model.parameters(), 1e-04, weight_decay=5e-04)

plotter, fig, ax = create_plot(('loss', 'reg_loss', 'cls_loss', 'Precision', 'Recall'), 
                               1, figsize=(8, 12))

<IPython.core.display.Javascript object>

In [35]:
for _ in range(5):
    train_epoch()
    plotter.plot()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


Tboxes shape: (0,)
Targer Shape: (400, 4)


IndexError: index 324 is out of bounds for dimension 0 with size 324

In [ ]:
for i in range(len(colors)):
    print(colors[i].shape[0] == boxes[i].shape[0])

In [ ]:
%matplotlib notebook
plt.imshow(images[3].reshape(300,300,3))

In [ ]:
boxes.dtype

In [ ]:
images = images.int()
print(images.dtype)