In [1]:
import numpy as np

"""
Rectangle class that allows for easier use/access to the four coordinates of a bounding box
"""
class rectangle:
    def __init__(self, xmin, ymin, xmax, ymax):
        self.xmin = xmin
        self.ymin = ymin
        self.xmax = xmax
        self.ymax = ymax
    
    def __repr__(self):
        return str(np.array([self.xmin, self.ymin, self.xmax, self.ymax]))
    
    
    def toArray(self):
        return np.array([self.xmin, self.ymin, self.xmax, self.ymax])
    

In [28]:
dataset = []
import xml.etree.ElementTree as ET
a = []
green = []
red = []
xmin = 0
ymin = 0
xmax = 0
ymax = 0
tree = ET.parse('images_new_resized/green_new_labels/00000007.xml')
root = tree.getroot()
for child in root:
    if child.tag == 'object' :
        for subchild in child:
            if subchild.tag == 'bndbox':
                for subsubchild in subchild:
                    if subsubchild.tag == 'xmin':
                        xmin = int(subsubchild.text)
                    elif subsubchild.tag == 'ymin':
                        ymin = int(subsubchild.text)
                    elif subsubchild.tag == 'xmax':
                        xmax = int(subsubchild.text)
                    elif subsubchild.tag == 'ymax':
                        ymax = int(subsubchild.text)
                a.append(rectangle(xmin, ymin, xmax, ymax).toArray())


                
for l in range(len(a)):
    a[l] = np.array(a[l])
print(np.array(a))

[[128  64 173 132]
 [ 10 207  53 274]
 [ 59 209  96 278]
 [103 211 134 274]
 [142 212 173 272]
 [183 210 210 276]
 [217 214 247 278]
 [254 213 287 280]]


In [48]:
boxes = []
for i in range(10):
    tmp = []
    tree = ET.parse('images_new_resized/green_new_labels/0000000'+str(i)+'.xml')
    root = tree.getroot()
    for child in root:
        if child.tag == 'object' :
            for subchild in child:
                if subchild.tag == 'bndbox':
                    for subsubchild in subchild:
                        if subsubchild.tag == 'xmin':
                            xmin = int(subsubchild.text)
                        elif subsubchild.tag == 'ymin':
                            ymin = int(subsubchild.text)
                        elif subsubchild.tag == 'xmax':
                            xmax = int(subsubchild.text)
                        elif subsubchild.tag == 'ymax':
                            ymax = int(subsubchild.text)
                    tmp.append(rectangle(xmin, ymin, xmax, ymax).toArray())
    print(tmp)
    boxes.append(np.array(tmp))
    if len(boxes) == 0:
        boxes.append(np.zeros(4))
        
for i in range(10,100):
    try:
        tmp = []
        tree = ET.parse('images_new_resized/green_new_labels/000000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp.append(rectangle(xmin, ymin, xmax, ymax).toArray())
        print(tmp)
        boxes.append(np.array(tmp))
        if len(boxes) == 0:
            boxes.append(np.zeros(4))
    except:
        boxes.append(np.zeros(4))
        
for i in range(100,480):
    try:
        tmp = []
        tree = ET.parse('images_new_resized/green_new_labels/00000'+str(i)+'.xml')
        root = tree.getroot()
        for child in root:
            if child.tag == 'object' :
                for subchild in child:
                    if subchild.tag == 'bndbox':
                        for subsubchild in subchild:
                            if subsubchild.tag == 'xmin':
                                xmin = int(subsubchild.text)
                            elif subsubchild.tag == 'ymin':
                                ymin = int(subsubchild.text)
                            elif subsubchild.tag == 'xmax':
                                xmax = int(subsubchild.text)
                            elif subsubchild.tag == 'ymax':
                                ymax = int(subsubchild.text)
                        tmp.append(rectangle(xmin, ymin, xmax, ymax).toArray())
        print(tmp)
        boxes.append(np.array(tmp))
        if len(boxes) == 0:
            boxes.append(np.zeros(4))
    except:
        boxes.append(np.zeros(4))
        
print(len(boxes))

[array([117, 126, 160, 176])]
[array([ 50,  44, 256, 266])]
[array([ 73,  22, 279, 261])]
[array([112, 103, 178, 203])]
[array([ 96, 123, 163, 184])]
[array([169, 132, 230, 193])]
[array([114,  96, 203, 241])]
[array([128,  64, 173, 132]), array([ 10, 207,  53, 274]), array([ 59, 209,  96, 278]), array([103, 211, 134, 274]), array([142, 212, 173, 272]), array([183, 210, 210, 276]), array([217, 214, 247, 278]), array([254, 213, 287, 280])]
[array([172,  41, 270, 230])]
[array([ 95,  82, 165, 239])]
[array([ 30, 178,  76, 239])]
[array([100,  84, 191, 220])]
[array([147, 145, 227, 203])]
[array([145, 106, 185, 200])]
[array([ 83, 152, 178, 246])]
[array([179, 166, 239, 260])]
[array([117, 138, 166, 195])]
[array([143, 146, 174, 193])]
[array([224, 121, 262, 196])]
[array([ 39,  15, 283, 271])]
[array([100,  63, 181, 166])]
[array([ 91,  91, 226, 220])]
[array([159,  57, 184,  90])]
[array([113, 120, 188, 185])]
[array([ 52,  14, 275, 227])]
[array([ 40, 159,  97, 237])]
[array([100,  89,